<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- This file was created with the aha Ansi HTML Adapter. http://ziz.delphigl.com/tool_aha.php -->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="application/xml+xhtml; charset=UTF-8" />
<title>verification_results.log</title>
</head>
<body>
<pre>
Script started on Wed 20 Jan 2016 02:53:12 PM PST
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/beam_elastic_9dof/bending
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/beam_elastic_9dof/frame
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/beam_elastic_9dof/axial
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/truss
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/imposed_motion
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;reportmore.py&quot;, line 39, in &lt;module&gt;
    current1=find_max_disp_step1(h5name);
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 36, in find_max_disp_step1
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/DRM_1D
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;reportmore.py&quot;, line 39, in &lt;module&gt;
    current1=find_max_disp_step1(h5name);
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 36, in find_max_disp_step1
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/displacement_control
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;reportmore.py&quot;, line 39, in &lt;module&gt;
    current1=find_max_disp_step1(h5name);
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 36, in find_max_disp_step1
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/4ANDES/irregular_shape/shape2
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/4ANDES/irregular_shape/shape3
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/4ANDES/irregular_shape/shape1
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/4ANDES/elastic_element
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
^Z[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/4ANDES/profileSPD
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/4ANDES/square_plate/clamped
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
^CTraceback (most recent call last):
  File &quot;report.py&quot;, line 2, in &lt;module&gt;
    import h5py
  File &quot;/usr/lib/python2.7/dist-packages/h5py/__init__.py&quot;, line 16, in &lt;module&gt;
    from h5py import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
  File &quot;h5t.pxd&quot;, line 14, in init h5py.h5a (h5py/h5a.c:6112)
  File &quot;numpy.pxd&quot;, line 66, in init h5py.h5t (h5py/h5t.c:17955)
  File &quot;/usr/lib/python2.7/dist-packages/numpy/__init__.py&quot;, line 153, in &lt;module&gt;
    from . import add_newdocs
  File &quot;/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py&quot;, line 13, in &lt;module&gt;
    from numpy.lib import add_newdoc
  File &quot;/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py&quot;, line 8, in &lt;module&gt;
    from .type_check import *
  File &quot;/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py&quot;, line 11, in &lt;module&gt;
    import numpy.core.numeric as _nx
  File &quot;/usr/lib/python2.7/dist-packages/numpy/core/__init__.py&quot;, line 11, in &lt;module&gt;
    from . import numeric
  File &quot;/usr/lib/python2.7/dist-packages/numpy/core/numeric.py&quot;, line 5, in &lt;module&gt;
    import collections
  File &quot;/usr/lib/python2.7/collections.py&quot;, line 17, in &lt;module&gt;
    from thread import get_ident as _get_ident
KeyboardInterrupt
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/4ANDES/square_plate/simply_supported
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/4ANDES/different_Poisson
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/4ANDES/self_weight
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
^Z^X[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/4ANDES/umfpack
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/4ANDES/circular_plate/simply_support
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/4ANDES/circular_plate/clamped
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/27NodeBrick/irregular_shape/shape2
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/27NodeBrick/irregular_shape/shape3
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
^Z[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/27NodeBrick/irregular_shape/shape1
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/27NodeBrick/elastic_element
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
^CTraceback (most recent call last):
  File &quot;report.py&quot;, line 2, in &lt;module&gt;
    import h5py
  File &quot;/usr/lib/python2.7/dist-packages/h5py/__init__.py&quot;, line 21, in &lt;module&gt;
    from h5py.highlevel import *
  File &quot;/usr/lib/python2.7/dist-packages/h5py/highlevel.py&quot;, line 12, in &lt;module&gt;
    from _hl.files import File
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 17, in &lt;module&gt;
    from h5py import version
  File &quot;/usr/lib/python2.7/dist-packages/h5py/version.py&quot;, line 10, in &lt;module&gt;
    from . import h5 as _h5
KeyboardInterrupt
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/27NodeBrick/profileSPD
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
^X[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/27NodeBrick/square_plate/clamped
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/27NodeBrick/square_plate/simply_supported
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/27NodeBrick/different_Poisson
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/27NodeBrick/self_weight
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
^CTraceback (most recent call last):
  File &quot;status.py&quot;, line 2, in &lt;module&gt;
    import h5py
  File &quot;/usr/lib/python2.7/dist-packages/h5py/__init__.py&quot;, line 16, in &lt;module&gt;
    from h5py import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
  File &quot;h5t.pxd&quot;, line 14, in init h5py.h5a (h5py/h5a.c:6112)
  File &quot;numpy.pxd&quot;, line 66, in init h5py.h5t (h5py/h5t.c:17955)
  File &quot;/usr/lib/python2.7/dist-packages/numpy/__init__.py&quot;, line 169, in &lt;module&gt;
    from . import polynomial
  File &quot;/usr/lib/python2.7/dist-packages/numpy/polynomial/__init__.py&quot;, line 24, in &lt;module&gt;
    from .hermite_e import HermiteE
  File &quot;/usr/lib/python2.7/dist-packages/numpy/polynomial/hermite_e.py&quot;, line 1746, in &lt;module&gt;
    exec(polytemplate.substitute(name='HermiteE', nick='herme', domain='[-1,1]'))
  File &quot;&lt;string&gt;&quot;, line 2, in &lt;module&gt;
KeyboardInterrupt
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/27NodeBrick/surface_load
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
^X[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/27NodeBrick/circular_plate/clamped
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/27NodeBrick/circular_plate/simply_supported
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
^CTraceback (most recent call last):
  File &quot;report.py&quot;, line 2, in &lt;module&gt;
    import h5py
  File &quot;/usr/lib/python2.7/dist-packages/h5py/__init__.py&quot;, line 16, in &lt;module&gt;
    from h5py import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
  File &quot;h5t.pxd&quot;, line 14, in init h5py.h5a (h5py/h5a.c:6112)
  File &quot;numpy.pxd&quot;, line 66, in init h5py.h5t (h5py/h5t.c:17955)
  File &quot;/usr/lib/python2.7/dist-packages/numpy/__init__.py&quot;, line 169, in &lt;module&gt;
    from . import polynomial
  File &quot;/usr/lib/python2.7/dist-packages/numpy/polynomial/__init__.py&quot;, line 22, in &lt;module&gt;
    from .legendre import Legendre
  File &quot;/usr/lib/python2.7/dist-packages/numpy/polynomial/legendre.py&quot;, line 1768, in &lt;module&gt;
    exec(polytemplate.substitute(name='Legendre', nick='leg', domain='[-1,1]'))
  File &quot;&lt;string&gt;&quot;, line 2, in &lt;module&gt;
KeyboardInterrupt
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/beam_elastic_12dof/bending
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
^ZTraceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
^X^CTraceback (most recent call last):
  File &quot;status.py&quot;, line 2, in &lt;module&gt;
    import h5py
  File &quot;/usr/lib/python2.7/dist-packages/h5py/__init__.py&quot;, line 16, in &lt;module&gt;
    from h5py import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
  File &quot;h5t.pxd&quot;, line 14, in init h5py.h5a (h5py/h5a.c:6112)
  File &quot;numpy.pxd&quot;, line 66, in init h5py.h5t (h5py/h5t.c:17955)
  File &quot;/usr/lib/python2.7/dist-packages/numpy/__init__.py&quot;, line 169, in &lt;module&gt;
    from . import polynomial
  File &quot;/usr/lib/python2.7/dist-packages/numpy/polynomial/__init__.py&quot;, line 24, in &lt;module&gt;
    from .hermite_e import HermiteE
  File &quot;/usr/lib/python2.7/dist-packages/numpy/polynomial/hermite_e.py&quot;, line 1746, in &lt;module&gt;
    exec(polytemplate.substitute(name='HermiteE', nick='herme', domain='[-1,1]'))
  File &quot;&lt;string&gt;&quot;, line 2, in &lt;module&gt;
KeyboardInterrupt
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
^Z[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/20NodeBrick/different_Poisson
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
^XTraceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
^CTraceback (most recent call last):
  File &quot;/usr/lib/python2.7/site.py&quot;, line 563, in &lt;module&gt;
    main()
  File &quot;/usr/lib/python2.7/site.py&quot;, line 545, in main
    known_paths = addusersitepackages(known_paths)
  File &quot;/usr/lib/python2.7/site.py&quot;, line 272, in addusersitepackages
    user_site = getusersitepackages()
  File &quot;/usr/lib/python2.7/site.py&quot;, line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File &quot;/usr/lib/python2.7/site.py&quot;, line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File &quot;/usr/lib/python2.7/sysconfig.py&quot;, line 578, in get_config_var
    return get_config_vars().get(name)
  File &quot;/usr/lib/python2.7/sysconfig.py&quot;, line 505, in get_config_vars
    import re
  File &quot;/usr/lib/python2.7/re.py&quot;, line 105, in &lt;module&gt;
    import sre_compile
  File &quot;/usr/lib/python2.7/sre_compile.py&quot;, line 13, in &lt;module&gt;
    import _sre, sys
KeyboardInterrupt
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
Traceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
cp: cannot stat ‘./scripts/Makefile’: No such file or directory
^Z[==========] Running test cases...
[Location  ] /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/test_cases/20NodeBrick/umfpack
./scripts/test.sh: line 27: /home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/bin/essi: No such file or directory
^XTraceback (most recent call last):
  File &quot;report.py&quot;, line 33, in &lt;module&gt;
    current=find_max_disp(file_in.readline());
  File &quot;/home/yuan/git_dir/git_ucd/BorisJeremic/Real-ESSI_autoTest/test_suite/scripts/essi_max_disp_fun.py&quot;, line 11, in find_max_disp
    h5file_in=h5py.File(h5in_file_name,&quot;r&quot;)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File &quot;/usr/lib/python2.7/dist-packages/h5py/_hl/files.py&quot;, line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File &quot;h5f.pyx&quot;, line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
^C[----------]
[statistics] Passed cases / All cases= 0/34 
</pre>
</body>
</html>
